# Auto-generated by tools/modularize_ui.py
import pygame, pygame_gui
from typing import Optional, List, Dict, Tuple

# Core & Engine imports (keep broad to avoid missing names during split)
try:
    from core.save_system import Career, save_career, load_career, simulate_week_ai
except Exception:
    pass
try:
    from engine import Team, Fighter, Weapon, TBCombat, Event, layout_teams_tiles
except Exception:
    try:
        from engine.model import Team, Fighter, Weapon
        from engine.tbcombat import TBCombat, Event
        from engine.grid import layout_teams_tiles
    except Exception:
        pass


class TableState:
    def __init__(self, app):
        self.app = app; self.ui = pygame_gui.UIManager(app.screen.get_size()); self._build_ui()

    def _build_ui(self):
        w,h = self.app.screen.get_size()
        self.lbl = pygame_gui.elements.UILabel(pygame.Rect(16,16,w-32,32), "Table", self.ui)
        self.btn_back = pygame_gui.elements.UIButton(pygame.Rect(w-16-120,16,120,32),"Back", self.ui)
        self.box = pygame_gui.elements.UITextBox(
            self._html_table(),
            pygame.Rect(16,64,w-32,h-80),
            manager=self.ui
        )

    def _html_table(self):
        try:
            rows = ["<b>Pos  Team                      Pts  W-D-L</b>"]
            tab = self.app.career.table  # list of {tid, pts, w,d,l}
            sortd = sorted(tab, key=lambda r: (-r["pts"], -(r["w"]), r["l"]))
            for i, row in enumerate(sortd, start=1):
                name = self.app.career.get_team(row["tid"])["name"]
                rows.append(f"{i:>2}. {name:24}  {row['pts']:>3}  {row['w']}-{row['d']}-{row['l']}")
            return "<br>".join(rows)
        except Exception:
            return "No table."

    def handle(self, event):
        if event.type == pygame.VIDEORESIZE:
            self.ui.set_window_resolution(event.size); self._build_ui()
        pressed = (event.type == pygame.USEREVENT and getattr(event, "user_type", None) == pygame_gui.UI_BUTTON_PRESSED) \
                  or (event.type == pygame_gui.UI_BUTTON_PRESSED)
        if pressed and event.ui_element == self.btn_back:
            self.app.set_state(ManagerMenuState(self.app))
        self.ui.process_events(event)

    def update(self, dt): self.ui.update(dt)
    def draw(self, surf): surf.fill(DARK); self.ui.draw_ui(surf)
